mode = "light"

accent = "#005FB8"
selection = "#ADD6FF"
muted = "#666666"

background = "#FFFFFF"
dark_background = "#F8F8F8"
darker_background = "#F2F2F2"
lighter_background = "#FFFFFF"

foreground = "#3B3B3B"
dark_foreground = "#6E7681"
light_foreground = "#555555"
bright_foreground = "#A5A5A5"

red = "#CD3131"
green = "#107C10"
yellow = "#949800"
blue = "#0451A5"
magenta = "#BC05BC"
cyan = "#0598BC"
orange = "#949800"

bright_red = "#CD3131"
bright_green = "#14CE14"
bright_yellow = "#B5BA00"
bright_blue = "#0451A5"
bright_magenta = "#BC05BC"
bright_cyan = "#0598BC"

selection_background = "#ADD6FF"
selection_foreground = "#FFFFFF"
comment = "#008000"